### ISSUE TITLE
Selector text is in black in Styles

### ISSUE THREAD

**Issue by simonexmachina** [remybach/chrome-twilight#1]
<img src="http://imgur.com/lVmjz.png" />

**Comment by simonexmachina** [comment]
It looks like only the first (or maybe it's the active?) selector is in black, and the one after the comma in the picture is a readable colour.

BTW I'm using Chrome Canary.

**Comment by remybach** [comment]
Yeah, I noticed this on Friday as well and looked into it briefly. It seems to be one of the Chrome User Agent styles overriding the custom one. Now that you point it out though, it could well be that it's the active one (which is a pretty cool feature actually).

I should be able to look into this later today. Thanks for the letting me know it's happening to you.

**Comment by remybach** [comment]
Bingo! You were right... the Chrome team must've added new styles for when the selector matches what you have highlighted in the DOM. Nice touch!

I've just pushed an update that fixes that and adds colour for media queries.

**Comment by simonexmachina** [comment]
Awesome, thanks. Have you considered using SASS for future versions? It'd
certainly make it easier to tweak the colours.

Cheers,

Simon

**Comment by remybach** [comment]
Yeah, I love SASS... I might update to that at some point actually. It'll definitely make everyone's lives easier!

**Comment by simonexmachina** [comment]
Awesome! Please do. I'll watch the repo. I've been thinking about making a
SASS framework with mixins variables to make it easier for people's colour
schemes to stay up to date with Chrome changes. No time right now, but I'll
stay tuned and may be able to contribute soon.

Cheers,

Simon

**Comment by remybach** [comment]
Just a heads up: it's come to my attention that someone else is already half way through making a really cool and useful tool for this so I wouldn't waste my time on the SASS framework if I was you :)

**Comment by simonexmachina** [comment]
Sounds great, do you have a link?

Cheers,

Simon

**Comment by remybach** [comment]
It's still got quite a bit of work to be done, but it's here: https://github.com/wesbos/chromeio
